# In your static/admin/config.yml file

backend: 
    name: github
    repo: haydn5/netlify-cms-test-2

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          - {label: Image 1, name: image1, widget: image}
          - {label: Image 1 - Alt Info, name: image1alt, widget: string }
          - {label: Image 2, name: image2, widget: image}
          - {label: Image 2 - Alt Info, name: image2alt, widget: string }
          - {label: Image 3, name: image3, widget: image}
          - {label: Image 3 - Alt Info, name: image3alt, widget: string }
          - {label: Image 4, name: image4, widget: image}
          - {label: Image 4 - Alt Info, name: image4alt, widget: string }
